"use client"
import { useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { useSerie, saveProg } from "../../../../lib/useSerieLogic"
import { ListaEps } from "../../../../components/ListaEps"
export default function Detalhe(){
 const {id}=useParams(); const r=useRouter(); const {s,p,setP,st,setSt,tm,se,err,supa}=useSerie(id)
 const [op,setOp]=useState(1); const [rem,setRem]=useState(false)
 const tog=(a,b)=>{ let k=a+"-"+b,n=p.includes(k)?p.filter(x=>x!==k):[...p,k]; setP(n); saveProg(id,n); if(n.length&&st==="quero_assistir"){ setSt("assistindo"); try{localStorage.setItem("status-"+id,"assistindo")}catch{}} }
 const setStt=v=>{ setSt(v); try{localStorage.setItem("status-"+id,v);localStorage.setItem("_upd",Date.now())}catch{}; if(v==="ja_maratonei"){let a=["100%"];setP(a);saveProg(id,a)} else if(v==="quero_assistir"){setP([]);saveProg(id,[])} }
 const mark=(sn,tot)=>{ let e=Array.from({length:tot},(_,i)=>sn+"-"+(i+1)),all=e.every(k=>p.includes(k)),n=all?p.filter(x=>!x.startsWith(sn+"-")):Array.from(new Set([...p.filter(x=>x!=="100%"),...e])); setP(n); saveProg(id,n) }
 const del=async()=>{ if(!confirm(`Abandonar "${s?.titulo}"?`))return; setRem(true); try{localStorage.removeItem("status-"+id);localStorage.removeItem("progress-"+id);await supa.from("series").delete().eq("id",id);r.push("/")}catch(e){alert(e.message);setRem(false)} }
 if(err)return <div style={{background:"#08162e",minHeight:"100vh",color:"#ff8a8a",padding:20}}><button onClick={()=>r.back()}>‹ Voltar</button><div style={{marginTop:20}}>Erro: {err}</div></div>
 if(!s)return <div style={{background:"#08162e",minHeight:"100vh",display:"grid",placeItems:"center",color:"#fff"}}>Carregando...</div>
 let tot=tm?.number_of_episodes||se.reduce((a,b)=>a+(b.episode_count||0),0)||10,wd=p.filter(x=>x!=="100%").length,pct=p.includes("100%")?100:tot?Math.round(wd/tot*100):0
 return (<div style={{minHeight:"100vh",background:"#0A1836",color:"#fff",paddingBottom:90}}><div style={{height:56,display:"flex",justifyContent:"space-between",padding:"0 16px",alignItems:"center",position:"sticky",top:0,background:"#0A1836",zIndex:10,borderBottom:"1px solid #ffffff10"}}><div style={{display:"flex",gap:10,alignItems:"center"}}><button onClick={()=>r.back()} style={{width:32,height:32,borderRadius:999,border:0}}>‹</button><b style={{fontSize:14,maxWidth:160,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis"}}>{s.titulo}</b></div><button onClick={del} style={{height:30,padding:"0 10px",borderRadius:999,border:"1px solid #ff5a5a33",background:"#ff5a5a14",color:"#ff8a8a",fontSize:11,fontWeight:700}}>{rem?"...":"🗑 Abandonar"}</button></div><div style={{maxWidth:860,margin:"0 auto"}}><div style={{display:"flex",gap:14,padding:16}}><img src={s.poster?`https://image.tmdb.org/t/p/w300${s.poster}`:""} style={{width:110,height:165,borderRadius:14,objectFit:"cover",background:"#122042"}} alt=""/><div style={{flex:1}}><div style={{fontWeight:900,fontSize:15}}>{s.titulo}</div><div style={{fontSize:11,opacity:.5,marginTop:4}}>{se.length} temp • {tot} eps</div><div style={{marginTop:12,height:6,background:"#ffffff18",borderRadius:999,overflow:"hidden"}}><div style={{width:pct+"%",height:"100%",background:"#FFD400"}}/></div><div style={{display:"flex",justifyContent:"space-between",fontSize:11,marginTop:6}}><span style={{opacity:.5}}>{wd}/{tot}</span><span style={{color:"#FFD400",fontWeight:800}}>{pct}%</span></div></div></div><div style={{display:"flex",gap:6,padding:"0 16px",flexWrap:"wrap"}}><button onClick={()=>setStt("assistindo")} style={{height:36,padding:"0 14px",borderRadius:999,border:0,background:st==="assistindo"?"#fff":"#ffffff14",color:st==="assistindo"?"#000":"#fff",fontWeight:700}}>Assistindo</button><button onClick={()=>setStt("quero_assistir")} style={{height:36,padding:"0 14px",borderRadius:999,border:0,background:st==="quero_assistir"?"#fff":"#ffffff14",color:st==="quero_assistir"?"#000":"#fff"}}>Quero assistir</button><button onClick={()=>setStt("ja_maratonei")} style={{height:36,padding:"0 14px",borderRadius:999,border:"1px solid #FFD400",background:st==="ja_maratonei"?"#FFD400":"transparent",color:st==="ja_maratonei"?"#000":"#FFD400",fontWeight:900}}>✓ Já maratonei</button></div><div style={{padding:16}}>{se.map(x=><ListaEps key={x.season_number} sn={x.season_number} total={x.episode_count||8} prog={p} tog={tog} poster={s.poster} sinopse={s.sinopse} tmdbId={s.tmdb_id} open={op===x.season_number} setOpen={setOp} mark={mark} />)}</div></div></div>)
}
