"use client"
import { useEffect, useState } from "react"
import { getSupa } from "../../lib/supabase"
import { BottomNav } from "../../components/BottomNav"
import { MOLDURAS, getMoldura } from "../../lib/moldurasLogic"
const supa=getSupa()
const hoje=()=>new Date().toISOString().slice(0,10)
export default function Perfil(){
const [nome,setNome]=useState("Você")
const [st,setSt]=useState({t:0,m:0,h:0,n:1,xp:0})
const [cks,setCks]=useState([])
const [seq,setSeq]=useState(0)
const [molduraId,setMolduraId]=useState("padrao")
const [showLoja,setShowLoja]=useState(false)
useEffect(()=>{const n=localStorage.getItem("perfil-nome")||"Você";const m=localStorage.getItem("perfil-moldura")||"padrao";setNome(n);setMolduraId(m);(async()=>{let sT=0,fT=0,mc=0,hr=0;try{const a=await supa.from("series").select("id");const b=await supa.from("filmes").select("id");sT=a.data?.length||0;fT=b.data?.length||0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.includes("status-")&&localStorage.getItem(k)=="ja_assisti")mc++;if(k?.startsWith("progress-")){try{hr+=JSON.parse(localStorage.getItem(k)||"[]").length*0.7}catch{}}}}catch{}const c=JSON.parse(localStorage.getItem("checkins")||"[]");setCks(c);let sq=0;const d=new Date();for(let i=0;i<30;i++){const x=new Date();x.setDate(d.getDate()-i);if(c.includes(x.toISOString().slice(0,10)))sq++;else if(i>0)break}setSeq(sq);const xp=mc*100+Math.floor(hr*5)+fT*30+c.length*15;setSt({t:sT+fT,m:mc,h:Math.round(hr),n:Math.max(1,Math.floor(xp/150)+1),xp})})()},[])
const doCheck=()=>{const h=hoje();if(cks.includes(h))return;const n=[...cks,h];localStorage.setItem("checkins",JSON.stringify(n));location.reload()}
const escolher=(id,nivel)=>{if(st.n<nivel)return alert("Chegue no nível "+nivel+" para desbloquear!");localStorage.setItem("perfil-moldura",id);setMolduraId(id);setShowLoja(false)}
const dias=Array.from({length:30},(_,i)=>{const d=new Date();d.setDate(new Date().getDate()-(29-i));return d.toISOString().slice(0,10)})
const molduraAtual=getMoldura(molduraId)
return(<div className="min-h-screen bg-[#080B1F] text-white pb-24"><header className="h-14 flex items-center justify-between px-4 border-b border-white/10 sticky top-0 bg-[#080B1F] z-10"><b>Perfil</b><button onClick={()=>setShowLoja(!showLoja)} className="bg-white/10 px-3 py-1.5 rounded-full text-xs font-bold">🎨 Molduras</button></header><main className="max-w- mx-auto p-3.5 flex flex-col gap-3">
<div className="bg-[#12182F] border border-white/10 rounded-2xl p-4 flex items-center gap-3"><div className={`w-14 h-14 rounded-full grid place-items-center text-black font-black text-xl border-2 ${molduraAtual.borda} bg-[#FFD400]`}>{nome[0]}</div><div className="flex-1"><div className="font-black">{nome}</div><div className="text-xs opacity-50">Nível {st.n} • {st.xp} XP • 🔥 {seq} dias • {molduraAtual.nome}</div><div className="h-1.5 bg-white/10 rounded-full mt-2 overflow-hidden"><div className="h-full bg-[#FFD400]" style={{width:(st.xp%150)/1.5+"%"}}/></div></div><button onClick={doCheck} className={`h-9 px-4 rounded-full font-black text-sm ${cks.includes(hoje())?"bg-green-500 text-white":"bg-[#FFD400] text-black"}`}>{cks.includes(hoje())?"✓":"Check-in"}</button></div>
{showLoja&&<div className="bg-[#12182F] border border-yellow-400/20 rounded-2xl p-3.5"><div className="font-extrabold text- mb-3">Loja de Molduras • Nível {st.n}</div><div className="grid grid-cols-3 gap-2.5">{MOLDURAS.map(m=>{const ok=st.n>=m.nivel;const ativo=m.id===molduraId;return<div key={m.id} onClick={()=>escolher(m.id,m.nivel)} className={`rounded-xl p-2.5 text-center border cursor-pointer ${ativo?"border-yellow-400 bg-yellow-400/10":"border-white/10 bg-white/[0.04]"} ${!ok?"opacity-40":""}`}><div className={`w-10 h-10 mx-auto rounded-full grid place-items-center font-black border-2 ${m.borda}`} style={{background:m.preview,color:"#000"}}>{nome[0]}</div><div className="text- font-bold mt-1.5">{m.nome}</div><div className="text- opacity-50">Nv {m.nivel}</div><div className="text- mt-1 font-black">{ativo?"Equipado":ok?"Desbloqueada":"Bloqueada"}</div></div>})}</div></div>}
<div className="grid grid-cols-3 gap-2.5"><div className="bg-[#12182F] border border-white/10 rounded-2xl p-3.5 text-center"><div className="text-xl font-black">{st.t}</div><div className="text- opacity-40">Títulos</div></div><div className="bg-[#12182F] border border-white/10 rounded-2xl p-3.5 text-center"><div className="text-xl font-black text-[#FFD400]">{st.m}</div><div className="text- opacity-40">Maratonadas</div></div><div className="bg-[#12182F] border border-white/10 rounded-2xl p-3.5 text-center"><div className="text-xl font-black">{st.h}h</div><div className="text- opacity-40">Tempo</div></div></div>
<div className="bg-[#12182F] border border-white/10 rounded-2xl p-3.5"><div className="font-extrabold text-">Calendário • 30 dias</div><div className="grid grid-cols-10 gap-1.5 mt-2.5">{dias.map(d=>{const ok=cks.includes(d);return<div key={d} className={`aspect-square rounded-lg grid place-items-center text- font-bold ${ok?"bg-green-500":"bg-white/10 opacity-35"}`}>{new Date(d).getDate()}</div>})}</div></div>
</main><BottomNav/></div>)}
