"use client"
import { useEffect, useState } from "react"
export function ListaEps({sn,total,prog,tog,poster,sinopse,tmdbId,open,setOpen,mark}){
 const [eps,setEps]=useState([]); const progT=Array.from({length:total}).filter((_,i)=>prog.includes(sn+"-"+(i+1))).length
 useEffect(()=>{ async function ld(){ if(!open||eps.length||!tmdbId)return; try{ let r=await fetch(`https://api.themoviedb.org/3/tv/${tmdbId}/season/${sn}?api_key=${process.env.NEXT_PUBLIC_TMDB_KEY}&language=pt-BR`); let j=await r.json(); setEps(j.episodes||[]) }catch{} } ld() },[open])
 return (<div style={{background:"#13244A",borderRadius:16,overflow:"hidden",border:"1px solid #ffffff0f",marginBottom:12}}>
  <button onClick={()=>setOpen(open?0:sn)} style={{width:"100%",display:"flex",justifyContent:"space-between",padding:"14px",background:"none",border:0,color:"#fff",cursor:"pointer"}}><b>Temporada {sn} • {progT}/{total}</b><span style={{width:26,height:26,borderRadius:999,background:"#ffffff14",display:"grid",placeItems:"center"}}>{open?"−":"+"}</span></button>
  {open&&<div style={{borderTop:"1px solid #ffffff0f"}}><div style={{padding:"10px 12px",display:"flex",justifyContent:"space-between",alignItems:"center",background:"#ffffff06"}}><span style={{fontSize:11,opacity:.6}}>{total} episódios</span><button onClick={()=>mark(sn,total)} style={{height:28,padding:"0 12px",borderRadius:999,border:0,background:"#FFD400",fontSize:11,fontWeight:800}}>{Array.from({length:total}).every((_,i)=>prog.includes(sn+"-"+(i+1)))?"Desmarcar tudo":"✓ Marcar todos"}</button></div>
   {Array.from({length:total}).map((_,i)=>{let n=i+1,k=sn+"-"+n,ck=prog.includes(k),ei=eps[i]; return (<div key={k} style={{display:"flex",gap:10,padding:"10px 12px",borderTop:"1px solid #ffffff08",background:ck?"#ffffff08":"transparent",alignItems:"center"}}><img src={ei?.still_path?`https://image.tmdb.org/t/p/w185${ei.still_path}`:poster?`https://image.tmdb.org/t/p/w185${poster}`:""} style={{width:76,height:44,borderRadius:8,objectFit:"cover",background:"#0A1836",flexShrink:0}} alt=""/><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{n}. {ei?.name||`Episódio ${n}`}</div><div style={{fontSize:10,opacity:.55,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden",lineHeight:"13px"}}>{ei?.overview||sinopse||"Sem resumo disponível."}</div></div><button onClick={()=>tog(sn,n)} style={{width:32,height:32,borderRadius:999,border:ck?"0":"2px solid #ffffff35",background:ck?"#FFD400":"transparent",display:"grid",placeItems:"center",cursor:"pointer",flexShrink:0}}><span style={{fontWeight:900,color:ck?"#000":"transparent"}}>✓</span></button></div>)})}
  </div>}</div>)
}
